// Database Models (generated by Prisma)
import type {
  User,
  College,
  Course,
  Review,
  Recruiter,
  SavedCollege,
  SavedComparison,
  ComparisonItem,
} from '@prisma/client'

export type {
  User,
  College,
  Course,
  Review,
  Recruiter,
  SavedCollege,
  SavedComparison,
  ComparisonItem,
} from '@prisma/client'

// API Response Types
export interface ApiResponse<T> {
  success: true
  data: T
}

export interface ApiError {
  success: false
  message: string
  errors?: Record<string, string[]>
}

export type ApiResult<T> = ApiResponse<T> | ApiError

// College Types
export interface CollegeWithRelations extends College {
  courses: Course[]
  reviews: Review[]
  recruiters: Recruiter[]
  _count?: {
    reviews: number
  }
}

export interface CollegeListItem {
  id: string
  name: string
  location: string
  description: string
  establishmentYear: number
  ranking: number | null
  rating: number
  fees: number
  thumbnail: string | null
  averagePackage: number | null
  _count?: {
    reviews: number
  }
}

// Search & Filter Types
export interface CollegeFilters {
  search?: string
  location?: string
  minRating?: number
  minFees?: number
  maxFees?: number
  page?: number
  limit?: number
}

export interface PaginatedResponse<T> {
  data: T[]
  pagination: {
    page: number
    limit: number
    total: number
    totalPages: number
  }
}

// Auth Types
export interface SignupInput {
  name: string
  email: string
  password: string
}

export interface LoginInput {
  email: string
  password: string
}

export interface AuthUser {
  id: string
  email: string
  name: string | null
}

// Comparison Types
export interface ComparisonCollege {
  id: string
  name: string
  location: string
  rating: number
  fees: number
  ranking: number | null
  averagePackage: number | null
  highestPackage: number | null
  establishmentYear: number
}

// Saved Items Types
export interface SavedCollegeItem {
  id: string
  collegeId: string
  college: CollegeListItem
  createdAt: Date
}
